# Generated by Django 3.2 on 2023-02-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseit', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
