# Generated by Django 3.2 on 2023-02-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseit', '0006_auto_20230221_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterflatmodeldata',
            fields=[
                ('flatmodelid', models.AutoField(db_column='flatModelID', primary_key=True, serialize=False)),
                ('flatmodel', models.TextField(blank=True, db_column='flatModel')),
            ],
            options={
                'db_table': 'MasterFlatModelData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masterflattypes',
            fields=[
                ('flattypeid', models.AutoField(db_column='flatTypeID', primary_key=True, serialize=False)),
                ('flattype', models.TextField(blank=True, db_column='flatType')),
            ],
            options={
                'db_table': 'MasterFlatTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masterpropertyrentaldata',
            fields=[
                ('rentalpropertyid', models.AutoField(db_column='rentalPropertyID', primary_key=True, serialize=False)),
                ('yyyymm', models.TextField(blank=True, db_column='YYYYMM')),
                ('townid', models.IntegerField(blank=True, db_column='townID')),
                ('block', models.TextField(blank=True)),
                ('streetid', models.IntegerField(blank=True, db_column='streetID')),
                ('flattypeid', models.IntegerField(blank=True, db_column='flatTypeID')),
                ('monthlyrent', models.IntegerField(blank=True, db_column='monthlyRent')),
            ],
            options={
                'db_table': 'MasterPropertyRentalData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masterpropertyresaledata',
            fields=[
                ('resalepropertyid', models.AutoField(db_column='resalePropertyID', primary_key=True, serialize=False)),
                ('yyyymm', models.TextField(blank=True, db_column='YYYYMM')),
                ('townid', models.IntegerField(blank=True, db_column='townID')),
                ('flattypeid', models.IntegerField(blank=True, db_column='flatTypeID')),
                ('block', models.TextField(blank=True)),
                ('streetid', models.IntegerField(blank=True, db_column='streetID')),
                ('floorareainsqm', models.TextField(blank=True, db_column='floorAreaInSqm')),
                ('flatmodelid', models.IntegerField(blank=True, db_column='flatModelID')),
                ('leasecommencedate', models.TextField(blank=True, db_column='leaseCommenceDate')),
                ('remainingleaseyears', models.TextField(blank=True, db_column='remainingLeaseYears')),
                ('resaleprice', models.DecimalField(blank=True, db_column='resalePrice', decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'MasterPropertyResaleData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Masterstreetdata',
            fields=[
                ('streetid', models.AutoField(db_column='streetID', primary_key=True, serialize=False)),
                ('streetname', models.TextField(blank=True, db_column='streetName')),
            ],
            options={
                'db_table': 'MasterStreetData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mastertowndata',
            fields=[
                ('townid', models.AutoField(db_column='townID', primary_key=True, serialize=False)),
                ('townname', models.TextField(blank=True, db_column='townName')),
            ],
            options={
                'db_table': 'MasterTownData',
                'managed': False,
            },
        ),
    ]
