# Generated by Django 3.2 on 2023-02-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseit', '0004_auto_20230221_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
