# Generated by Django 2.0.1 on 2023-02-24 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houseit', '0007_masterflatmodeldata_masterflattypes_masterpropertyrentaldata_masterpropertyresaledata_masterstreetda'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchMasterProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentOrSaleFlag', models.CharField(default='S', max_length=1)),
                ('yyyymm', models.CharField(default='', max_length=6)),
                ('flattype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseit.Masterflattypes')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseit.Masterstreetdata')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseit.Mastertowndata')),
            ],
        ),
    ]
