# Generated by Django 4.1.7 on 2023-03-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseit', '0008_searchmasterproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listedproperty',
            fields=[
                ('propertyid', models.AutoField(db_column='propertyID', primary_key=True, serialize=False)),
                ('propertyownerid', models.IntegerField(blank=True, db_column='propertyOwnerID', null=True)),
                ('propertyflattypeid', models.IntegerField(blank=True, db_column='propertyFlatTypeID', null=True)),
                ('propertyblock', models.TextField(blank=True, db_column='propertyBlock', null=True)),
                ('propertytownid', models.IntegerField(blank=True, db_column='propertyTownID', null=True)),
                ('propertyflatmodelid', models.IntegerField(blank=True, db_column='propertyFlatModelID', null=True)),
                ('propertystreetid', models.IntegerField(blank=True, db_column='propertyStreetID', null=True)),
                ('propertyage', models.IntegerField(blank=True, db_column='propertyAge', null=True)),
                ('floorareainsqm', models.IntegerField(blank=True, db_column='floorAreaInSqm', null=True)),
                ('saleorrentalflag', models.TextField(blank=True, db_column='saleOrRentalFlag', null=True)),
                ('askingmonthlyrent', models.IntegerField(blank=True, db_column='askingMonthlyRent', null=True)),
                ('leasecommencedate', models.DateField(blank=True, db_column='leaseCommenceDate', null=True)),
                ('remainingleaseyears', models.IntegerField(blank=True, db_column='remainingLeaseYears', null=True)),
                ('askingprice', models.IntegerField(blank=True, db_column='AskingPrice', null=True)),
                ('propertystatus', models.TextField(blank=True, db_column='propertyStatus', null=True)),
                ('propertyimage', models.FileField(blank=True, db_column='propertyImage', null=True, upload_to='')),
            ],
            options={
                'db_table': 'ListedProperty',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='searchMasterProperty',
        ),
    ]
